[package]
name = "rcas"
version = "0.1.0"
authors = ["willemml <willem@leit.so>"]
edition = "2018"
license = "GPL-3.0"
description = "CAS (Computer Algebra System) for no_std environements."
repository = "https://github.com/willemml/rcas"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = { version = "6", default-features = false }
arrayvec = { version = "0.7.2", default-features = false }
micromath = { version = "2.0.0", default-features = false }
heapless = "0.7.14"
